### ISSUE TITLE
Getting application Product name failing

### ISSUE THREAD

**Issue by stephzhan** [tlelievre26/distraction-desktop#12]
Getting product name either returns NULL or crashes the program for certain applications. 

For example, Firefox returns NULL despite the ProductName being listed in the VERSIONINFO header. And the video games that I've tested in my Steam library have either had missing VERSIONINFO headers or ProductName was missing. Finally, applications like SnippingTool have their ProductName listed as Microsoft� Windows� Operating System. Since Task Manager is able to get the application names of these apps, there is probably a work around for this issue.

**Comment by tlelievre26** [comment]
For now, we don't have a better solution than just dropping these apps from being written, with more time we could figure out alternative functions in WinAPI to supplement these instances.
